### ISSUE TITLE
Download link is broken - 404

### ISSUE THREAD

**Issue by iam8up** [darrikmazey/XymonQV#1]
https://github.com/downloads/darrikmazey/XymonQV/XymonQV.apk

**Comment by darrikmazey** [comment]
sorry.  that link is insanely old and a legacy function of github that seems to have changed.  i recommend the play store as your best option for downloading.

**Comment by ptroot** [comment]
It doesn't show up in the play store.
On Tue, Jun 7, 2016 at 6:24 AM Darrik Mazey notifications@github.com
wrote:

> sorry. that link is insanely old and a legacy function of github that
> seems to have changed. i recommend the play store as your best option for
> downloading.
> 
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub
> https://github.com/darrikmazey/XymonQV/issues/1#issuecomment-224252281,
> or mute the thread
> https://github.com/notifications/unsubscribe/AS3gfDHr3ADTwogLVtPCRjqWuZihKSIjks5qJVTRgaJpZM4IvNbR
> .
> 
> ## 
> 
> Paul.

sent from my iPad

**Comment by darrikmazey** [comment]
yeah, just realized google yanked it.  not sure when.  working on it.  i'll update here when it's back.  sorry about that.

**Comment by darrikmazey** [comment]
ok, i'm fairly certain i jumped through all the hoops, crossed i's, dotted t's, etc.  now it's up to google.  said it could be a few hours.

**Comment by ptroot** [comment]
Thanks Darrik,

Paul.

On Tue, Jun 7, 2016 at 8:08 AM Darrik Mazey notifications@github.com
wrote:

> ok, i'm fairly certain i jumped through all the hoops, crossed i's, dotted
> t's, etc. now it's up to google. said it could be a few hours.
> 
> —
> You are receiving this because you commented.
> 
> Reply to this email directly, view it on GitHub
> https://github.com/darrikmazey/XymonQV/issues/1#issuecomment-224274648,
> or mute the thread
> https://github.com/notifications/unsubscribe/AS3gfEXEcYEtSBHZM4uZkvFiCZQDpPbFks5qJW08gaJpZM4IvNbR
> .
> 
> ## 
> 
> Paul.

sent from my iPad

**Comment by darrikmazey** [comment]
ok, just checked and it's back up.  https://play.google.com/store/apps/details?id=com.darmasoft.xymon

if you really _need_ an apk, i can build one for you, but my machine isn't set up for it, so it'd take me a bit.  let me know.

**Comment by ptroot** [comment]
I got it! Thanks. I didn't need the app, I just wanted the app on my phone.

Paul.
On Tue, Jun 7, 2016 at 9:35 AM Darrik Mazey notifications@github.com
wrote:

> ok, just checked and it's back up.
> https://play.google.com/store/apps/details?id=com.darmasoft.xymon
> 
> if you really _need_ an apk, i can build one for you, but my machine
> isn't set up for it, so it'd take me a bit. let me know.
> 
> —
> You are receiving this because you commented.
> 
> Reply to this email directly, view it on GitHub
> https://github.com/darrikmazey/XymonQV/issues/1#issuecomment-224300120,
> or mute the thread
> https://github.com/notifications/unsubscribe/AS3gfPdLdyxLtsQFVSFhYNYoTg16glMBks5qJYGRgaJpZM4IvNbR
> .
> 
> ## 
> 
> Paul.

sent from my iPad

**Comment by darrikmazey** [comment]
:)
